### ISSUE TITLE
Merging elm and elm-test installation in setup instructions (README)

### ISSUE THREAD

**Issue by mrkiura** [AndelaOSP/shufflebox-frontend#24]
The packages `elm` and `elm-test` can be installed in one command:
```npm i -g elm elm-test```

**Comment by waiyaki** [comment]
@alexkiura Can this issue be expanded to cover updating other parts of the `README` as well? The current instructions are not a correct representation of how you actually run the app.

**Comment by mrkiura** [comment]
@waiyaki sure it can be. Which parts of the README would you like updated?

**Comment by waiyaki** [comment]
@alexkiura The points after installing deps
> - Start the webpack dev server.
> ```bash
> $ npm run dev
> ```
> - Visit localhost:3000. You should see the text shufflebox. i.e from src/Main.elm

**Comment by waiyaki** [comment]
@alexkiura Any updates on this?
